### ISSUE TITLE
nextage_moveit_config doesn't work with fake_joint_driver as it is

### ISSUE THREAD

**Issue by 7675t** [tork-a/fake_joint#2]
hrpsys_ros_bridge has action server for FollowJointTrajectoryAction, but the action name is fixed to "follow_joint_trajectory_action" (https://github.com/start-jsk/rtmros_common/blob/0beacf48e22cb19d4b591d10fd6f66ffb0301b35/hrpsys_ros_bridge/src/HrpsysJointTrajectoryBridge.cpp#L230)

However, the action name in ros_controllers is fixed to different name "follow_joint_trajectory" (https://github.com/ros-controls/ros_controllers/blob/f5dc6f2c31cfc76419f073c54a14ab04394ab919/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L304). As the result, we cannot use fake_joint_driver with the released nextage_moveit_config setting. Of course we can make new moveit_config in which we set the action_name to "follow_joint_trajectory" and it works, but I'd like to use the released version of nextage_moveit_config if possible.

I feel it is the best that hrpsys_ros_bridge change its action name to the regular naming "follow_joint_trajectory" following ros_control, but I know it is risky for users. The another option is to add a feature to specify action name to ros_controllers/joint_trajectory_controller, but I feel it is also unnecessary change for most users.

Any idea? @k-okada

**Comment by 7675t** [comment]
I have solved it by remapping.

https://github.com/ros-controls/ros_controllers/pull/355

**Comment by k-okada** [comment]
sorry for late, yes, using remapping is designed for this purpose.
