### ISSUE TITLE
release fake_joint_driver

### ISSUE THREAD

**Issue by Hardthof** [tork-a/fake_joint#5]
Would you mind bloom-releasing the package?

It would be nice to allow installing `fake_joint_driver` via apt without all the dependencies that fake_joint_launch lists and `rosdep install --from-paths src` pulls in

**Comment by 7675t** [comment]
Hi, you mean you want to install `fake_joint_driver` without installing `fake_joint_launch`?
Can't you do that with ``apt install ros-kinetic-fake-joint-driver``?

**Comment by Hardthof** [comment]
My bad, i did not mention I use melodic. I couldn't find a ros-kinetic-fake-joint-driver package.

**Comment by jschleicher** [comment]
Any chance of a _melodic_ release?

**Comment by 7675t** [comment]
Please give me a few days.

**Comment by 7675t** [comment]
I have bloomed them into melodic. Let's see for a while. https://github.com/ros/rosdistro/pull/23332

**Comment by jschleicher** [comment]
@7675t Thanks a lot!

**Comment by 7675t** [comment]
@jschleicher  It is very helpful if you check the released package working correctly. Currently I'm sticking to Kinetic for a while, so I don't have the Melodic environment.

**Comment by rfeistenauer** [comment]
It seems to be working fine

**Comment by 7675t** [comment]
Thanks!
